### ISSUE TITLE
Incorrect type for Releases

### ISSUE THREAD

**Issue by Greensleeves11** [contentstack/contentstack-management-javascript#145] opened 2024-05-09 07:24 UTC
Exported interface for **Releases** contains "locale" param (of "ReleaseData" type) -> https://github.com/contentstack/contentstack-management-javascript/blob/master/types/stack/release/index.d.ts#L11

It is inconsistent with what is indicated in API documentation for Releases, as the param name should be "release" -> https://www.contentstack.com/docs/developers/sdks/content-management-sdk/javascript/reference#release-create.

In order for creating release to work, we need to use param "release", but it ends up with following TS error: 

![Screenshot 2024-05-09 at 09 20 42](https://github.com/contentstack/contentstack-management-javascript/assets/88109081/934f9fb1-14c4-4592-ab79-6603affe32f3)

**Comment by harshithad0703** [comment] 2024-09-11 07:09
Hi @Greensleeves11 
We are not able to reproduce the issue here. When we export the release data we do get locale param in the data.

**Comment by harshithad0703** [comment] 2024-09-11 07:13
Hi @Greensleeves11 
The issue was resolved in [commit ](https://github.com/contentstack/contentstack-management-javascript/commit/3a09b1caeae884d774aaa3d8e5a2575232b1844e). Please check the latest version

cc: @sunil-lakshman @nadeem-cs

**Closed by harshithad0703** 2024-09-11 07:13 UTC
