### ISSUE TITLE
Invalid example code in documentation

### ISSUE THREAD

**Issue by MBO** [contentstack/contentstack-management-javascript#11] opened 2021-04-20 20:46 UTC
https://github.com/contentstack/contentstack-management-javascript/blob/master/jsdocs/Entry.html#L217

```Javascript
import * as contentstack from '@contentstack/management'
const client = contentstack.client()

client.stack({ api_key: 'api_key'}).contentType('content_type_uid').entry('uid').fetch()
.then((entry) => {
 entry.title = 'My New Entry'
 entry.description = 'Entry description'
 return Entry.update()
})
.then((entry) => console.log(entry))
```

The example is using `Entry`, which is not defined in this context. I guess it's supposed to be `entry` instead. It's repeated in few examples in that document.

**Comment by uttamukkoji** [comment] 2021-04-21 05:07
Thanks for raising issue @MBO, We will update the example and update here once we are done with the changes.

**Comment by uttamukkoji** [comment] 2021-05-26 12:02
Hi @MBO ,

We have updated the example for `update` function in `Entry` here is [link](https://github.com/contentstack/contentstack-management-javascript/blob/master/jsdocs/Entry.html#L217).  

As the issue is resolve I am closing this issue, if you have any query or issue we can re-open or create new issue.

**Closed by uttamukkoji** 2021-05-26 12:02 UTC
